[package]
name = "babilo-rs"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "babilo_rs_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
# Tauri
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-opener = "2"

# Serialización
serde = { version = "1", features = ["derive"] }
serde_json = "1"

# Audio
cpal = "0.15"
rubato = "0.15"
hound = "3.5"

# Procesamiento numérico
ndarray = "0.15"
ndarray-rand = "0.14"
realfft = "3.4"

# llama.cpp (versión compatible)
llama-cpp-2 = { git = "https://github.com/marek-hradil/llama-cpp-rs", branch = "update-version", features = ["mtmd", "vulkan"] }

# Utilidades
rand = "0.10.1"
rand_distr = "0.6.0"
tracing = "0.1"
byteorder = "1.5"

# Tu motor TTS (ort/Supertonic)
ort = { version = "2.0.0-rc.9", features = ["download-binaries"] }
